server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # İŞTE SİHİRLİ SATIR BURASI: 
        # "Dosyayı bulamazsan 404 verme, index.html'e yönlendir"
        try_files $uri $uri/ /index.html; 
    }
}